---
title: "CHI Trial Literature Review"
author: "Kayla Zhang, Damie Pak, Megan Greischar"
date: "2026-02-26"
output:
  bookdown::pdf_document2:
    toc: no
    fig_caption: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, eval = FALSE)
```

Packages we use
```{r}
library(here)
library(dplyr)
```

Here we combine shedding and symptom onset data from the CHI trials we 
collected into one plot.
```{r, fig.height = 6.5, fig.width = 6.5}
plot.pane <- function(dat, axis.labels) {
  
  plot(0, 0, xlim=c(0, 15), ylim=c(0, max(nrow(rightpane), nrow(leftpane)) * 4) + 3, 
       col = "white", xlab= "", ylab='', yaxt='n',
       xaxt="n")
  
  axis(1, at=seq(0, 15, by=3), mgp=c(0, 0.4, 0), tck=-0.02, cex.axis=0.8)
  axis.ystart <- 0
  
  for (v in 1:length(unique(dat$virus))) {
    currvirusdat <- dat[dat$virus==unique(dat$virus)[v],]
    numrows <- nrow(currvirusdat)
    currviruscol <- cols.df[cols.df$virus == currvirusdat$virus[1],]$col
    
    for (i in 1:nrow(currvirusdat)) {
      row <- currvirusdat[i,]

      if (row$individual) {
        citation <- substitute(
          bold(AUTHOR) * bolditalic(" et al.") * bold(COMMA_YEAR),
          list(
            AUTHOR = row$author,
            COMMA_YEAR = paste0(", ", row$year)
  )
)

      } else {
        citation <- substitute(
          AUTHOR * italic(" et al.") * COMMA_YEAR,
          list(
            AUTHOR = row$author,
            COMMA_YEAR = paste0(", ", row$year)
          )
        )
      }
    
      text(x=15, y=axis.ystart+i*4-2.25, labels=citation, cex=0.8, adj=1)
      
      points(row$shed.onset, 
               axis.ystart+i*4-2.25, 
               pch=16, 
               col=currviruscol, 
               cex=1.8)
      
      points(row$symptom.onset, 
               axis.ystart+i*4-2.25, 
               pch=15, 
               col="gray", 
               cex=0.9)
    
    }
    
      axis.yend <- axis.ystart + numrows * 4
      
      text(-0.25, axis.yend + 1, axis.labels[v], col=currviruscol, pos=4,
           cex=0.8)

      axis(2, at=seq(axis.ystart, axis.yend, by=4), col=currviruscol, lwd.ticks=0, 
           labels=rep("", length(seq(axis.ystart, axis.yend, by=4))), las=2, col.axis=currviruscol)
      axis.ystart <- axis.yend + 2
  }
}

chidata <- read.csv(here('data', 'chistudies.csv'))

leftpane <- chidata[chidata$virus %in% c('Influenza A', 'Rhinovirus'),]
rightpane <- chidata[chidata$virus %in% c('Norovirus', 'RSV', 'SARS-CoV-2'),]
cols.df <- data.frame(virus = unique(chidata$virus), 
                      col = c("#401594",
                              "#009E73", 
                              "#D55E00",
                              "#56B4E9",
                              "#CC79A7"))

labels.left <- c("Influenza A", "Rhinovirus")

labels.right <- c("Norovirus", "RSV", "SARS-CoV-2")

tiff('Figure 1.tiff', res=500, height=6.5, width=6.5,
     unit='in')
{
  par(bty='n', mfrow=c(1, 2), oma=c(1, 0, 0, 0), mar=c(1.1, 0.5, 0, 0))
  plot.pane(leftpane, labels.left)
  legend(x=1.75, y=15,
         legend=c("Shedding onset", "Symptom onset"),
         pch=c(16, 15), col=c("black", "grey"),
         pt.cex=c(1.8, 0.9), cex=0.8)
  mtext('Days post-inoculation', side=1, line=0, outer=TRUE,
        adj=0.5, cex=0.8)
  plot.pane(rightpane, labels.right)
}
dev.off()
```

We also plot the number of studies that matched our inclusion criteria over the
year of publication.
```{r}
studies_per_year <- chidata %>% group_by(year) %>% 
  summarize(count=n()) 

spy_model <- lm(log(count) ~ year,
                data=studies_per_year)

tiff('Figure S1.tiff', res=500, height=3.5, width=3.5, unit='in')

{
  plot(count ~ year, data=studies_per_year, bty='n', 
       xaxt='n', xlab='', yaxt='n', ylab='',
       las=2)
  
  axis(1, at=seq(min(studies_per_year$year),
                 max(studies_per_year$year),
                 by=1), labels=FALSE,
       mgp=c(0, 0.4, 0), tck=-0.02, las=2)
  
  text(x = seq(min(studies_per_year$year),
         max(studies_per_year$year), by=4),
       y = par("usr")[3] - 0.75,
       xpd = NA,
       labels = seq(min(studies_per_year$year),
         max(studies_per_year$year), by=4),
       srt=45)
  
  mtext('Year of publication', side=1, line=2.5)
  
  axis(2, mgp=c(0, 0.4, 0), tck=-0.02, las=2)
  
  mtext('Number of studies included\n in literature review', side=2, line=1.5)
}
dev.off()
```